
#' Add a `ggplot2::layer()` to model check visualization
#'
#' Since modelcheck uses `ggplot2` to implement the plots, you can use `mc_gglayer()`
#' to pass in a ggplot layer to the ggplot object generated by modelcheck.
#'
#' @param layers A ggplot layer or a list of ggplot layers.
#'
#' @export
#'
#' @examples
mc_gglayer = function(layers) {
  p = function(mc_setting = NULL) {
    if (!("gglayers" %in% names(mc_setting))) {
      mc_setting = c(list(gglayers = layers), mc_setting)
    } else {
      mc_setting$gglayers = c(mc_setting$gglayers, layers)
    }
    mc_setting
  }
  class(p) <- 'modelcheck'
  p
}
