
#' Add a `ggplot2::layer()` to model check visualization
#'
#' Since `vmc` uses `ggplot2` to implement the plots, you can use `mc_gglayer()`
#' to pass in a ggplot layer to the ggplot object generated by `vmc`
#'
#' @param layers A ggplot layer or a list of ggplot layers.
#'
#' @export
#'
#' @examples
#' library(ggplot2)
#'
#' mcplot(mpg_model) +
#'   mc_gglayer(coord_flip())
mc_gglayer = function(layers) {
  p = function(mc_setting = NULL) {
    if (!("gglayers" %in% names(mc_setting))) {
      mc_setting = c(list(gglayers = list(layers)), mc_setting)
    } else {
      mc_setting$gglayers = c(mc_setting$gglayers, list(layers))
    }
    mc_setting
  }
  class(p) <- 'modelcheck'
  p
}
