
#' Define the transformation applied to observed data
#'
#' `mc_observation_transformation()` defines the necessary transformation applied
#'  to the observed data before passing it to generate model check.
#'
#' The transformation is necessary when the distribution generated by the model
#'  is not predictive distributions. For example, when the distribution generated
#'  from `phi` parameter of beta distribution, the observed data can not be shown
#'  in model check directly but need to be transformed into the same scale of
#'  `phi`.
#' @param transform The transform function that is applied on the
#'  response variable in observed data. Default to be `NULL`. If `NULL`,
#'  `vmc` will use no transformation. The transform function takes an input
#'  of a data frame, e.g., the data frame passed to `observation`, containing a
#'  column named `observation` standing for observations of the response variable
#'  and several columns standing for the predictors in model (if any). The output
#'  of the transform function should be in the same form as the input, a data frame
#'  containing a column named observation and several columns for the predictors.
#'  This argument is useful when `mc_distribution` is set to a distribution
#'  that is in a different unit from the raw observation, e.g., `sigma` in Gaussian
#'  family models describes the variance of observation. See example for more details.
#' @param group A set of variables quoted by `ggplot2::vars()` and represents
#'  the group option used before applying the `transform` function.
#' @export
#' @examples
#' library(ggplot2)
#'
#' mcplot(mpg_model) +
#'   mc_distribution("sigma") +
#'   mc_observation_transformation(sd, vars(disp)) +
#'   mc_condition_on(x = vars(disp)) +
#'   mc_gglayer(coord_flip())
mc_observation_transformation = function(transform = NULL, group = NULL) {
  p = function(mc_setting = NULL) {
    # if (!is.null(transform)) {
    #   if (!is.null(group)) {
    #     transform_func = function(df) {
    #       df %>%
    #         group_by_at(group) %>%
    #         mutate(observation = transform(observation))
    #     }
    #   } else {
    #     transform_func = function(df) {
    #       df %>%
    #         mutate(observation = transform(observation))
    #     }
    #   }
    # } else {
    #   transform_func = NULL
    # }

    c(list(observation_transform = transform, observation_transform_group = group), mc_setting)
  }
  class(p) <- 'modelcheck'
  p
}
