#' Add components to a plot
#'
#' Similar to `ggplot2`, modelcheck uses `+` to allows you to start simple,
#' then get more and more complex, checking your work at each step.
#'
#' @section what can you add?:
#' You can add any of the following types of objects:
#'
#'   - An `mc_distribution()` object overrides the current model distribution
#'   - A uncertainty representation layer created by `mc_model_` or `mc_obs_`
#'     functions adds a visual layer for model distribution or observed data.
#'   - A comparative layout layer created by `mc_layout_` functions overrides
#'     the current comparative layout.
#'   - A `mc_condition_on()` object overrides the current conditional variables
#'     on x axis, rows, or columns.
#'   - A `mc_gglayer()` object adds a ggplot layer to the ggplot object
#'     generated by modelcheck.
#'   - A color object overrides the color/fill of model distribution and
#'     observed data in model check.
#'
#' You can also supply a list, in which case each element of the list will
#' be added in turn.
#'
#' @param e1 An object of class `modelcheck`.
#' @param e2 A model check component, as described below.
#'
#' @export
#' @method + modelcheck
#' @rdname modelcheck-add
#' @example
#' library(ggplot2)
#'
#' mcplot(mpg_model) +
#'   mc_distribution("mu") +
#'   mc_condition_on(x = vars(disp))
#'
#' # Alternatively, you can add multiple components with a list.
#' # This can be useful to return from a function.
#' mcplot(mpg_model) +
#'   list(mc_distribution("mu"),
#'        mc_condition_on(x = vars(disp)))
'+.modelcheck' = function(e1, e2) {
  e2name = deparse(substitute(e2))
  if (is(e2, "modelcheck")) {
    f = function(mc_setting = NULL) mc_setting %>% e2() %>% e1()
  } else if(is.list(e2)) {
    f = function(mc_setting = NULL) {
      for (o in rev(e2)) {
        mc_setting = mc_setting %>% o()
      }
      mc_setting %>% e1
    }
  } else {
    cli::cli_abort("Can't add {.var {e2name}} to a {.cls modelcheck} object.")
  }
  class(f) <- 'modelcheck'
  f
}

#' @export
print.modelcheck <- function(x, ...) {
  print(x())
}
